[[override]]
  name = "github.com/chromedp/cdproto"
  #revision = "a6af647da9b18c20313895d9d3f931162a220811"
  branch = "master"

[[override]]
  name = "github.com/chromedp/chromedp"
#  version = "0.2.0"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/evilsocket/islazy"
  branch = "master"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gin-contrib/gzip"
  version = "0.0.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"


[prune]
  go-tests = true
  unused-packages = true
